# Generated by Django 6.0.5 on 2026-06-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('status', models.CharField(choices=[('QUERO_LER', 'Quero Ler'), ('LENDO', 'Lendo'), ('CONCLUIDO', 'Concluído'), ('ABANDONADO', 'Abandonado')], default='QUERO_LER', max_length=20)),
                ('progresso', models.IntegerField(default=0)),
                ('nota', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
